// Code generated by mockery v1.0.0. DO NOT EDIT.

package storagemocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// DeleteObject provides a mock function with given fields: ctx, name
func (_m *Client) DeleteObject(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Name provides a mock function with given fields:
func (_m *Client) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// UploadObject provides a mock function with given fields: ctx, name, contentType, r
func (_m *Client) UploadObject(ctx context.Context, name string, contentType string, r io.Reader) error {
	ret := _m.Called(ctx, name, contentType, r)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader) error); ok {
		r0 = rf(ctx, name, contentType, r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
