// Code generated by mockery v1.0.0. DO NOT EDIT.

package profilemocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "github.com/foundation-13/gpr/pkg/types"
)

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

// GetReviews provides a mock function with given fields: ctx, userID
func (_m *Manager) GetReviews(ctx context.Context, userID string) (types.ReviewsDTO, error) {
	ret := _m.Called(ctx, userID)

	var r0 types.ReviewsDTO
	if rf, ok := ret.Get(0).(func(context.Context, string) types.ReviewsDTO); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(types.ReviewsDTO)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
